<?php 
/**
 * Compare Master functions and definitions
 *
 * When using a child theme you can override certain functions (those wrapped
 * in a function_exists() call) by defining them first in your child theme's
 * functions.php file. The child theme's functions.php file is included before
 * the parent theme's file, so the child theme functions would be used.
 *
 * @link https://codex.wordpress.org/Theme_Development
 * @link https://codex.wordpress.org/Child_Themes
 *
 * Functions that are not pluggable (not wrapped in function_exists()) are
 * instead attached to a filter or action hook.
 *
 * For more information on hooks, actions, and filters,
 * @link https://codex.wordpress.org/Plugin_API
 *
 * @package WordPress
 * @subpackage Compare_Master
 * @since Compare Master 1.0
 */

	
/**
* Adding child theme
*
*/
function c88_child_enqueue_styles() {
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/assets/dist/css/style.css',
        wp_get_theme()->get('Version')
    );
}

add_action( 'wp_enqueue_scripts', 'c88_child_enqueue_styles' );


/**
* Defines the main variables used in this theme (should be a unique name)
*
*/

defined('THEME_NAME') ? '' : define('THEME_NAME', 'cf');
defined('THEME_ASSETS') ? '' : define('THEME_ASSETS', get_stylesheet_directory_uri());
defined('THEME_ADMIN_ASSETS') ? '' : define('THEME_ADMIN_ASSETS', get_template_directory_uri().'/framework/admin');

/**
* Defines a google map API Key
*
*/

defined('GOOGLE_API_KEY') ? '' : define('GOOGLE_API_KEY', 'AIzaSyC3PHKAQrWC2w7lW89Xu1QsRPPtNgxDQr8');

/**
* Includes framework templates to set up theme options
*
*/

include_once(locate_template('framework/master/setup-theme.php'));

/**
* Initializes and registers custom theme options
*
*/

include_once(locate_template('framework/options/menu-options.php'));
include_once(locate_template('framework/options/theme-options.php'));
include_once(locate_template('framework/options/theme-options-blog.php'));
include_once(locate_template('framework/options/theme-options-forum.php'));
include_once(locate_template('framework/options/theme-options-microdata.php'));
include_once(locate_template('framework/options/theme-options-open-graph.php'));
include_once(locate_template('framework/options/theme-options-seo.php'));
include_once(locate_template('framework/options/page-options.php'));
include_once(locate_template('framework/options/post-options.php'));
include_once(locate_template('framework/options/category-options.php'));
include_once(locate_template('framework/options/widget-banner.php'));
include_once(locate_template('framework/options/widget-banner-content.php'));
include_once(locate_template('framework/options/widget-html-content.php'));
include_once(locate_template('framework/options/widget-most-discussed-posts.php'));
include_once(locate_template('framework/options/widget-newsletter.php'));
include_once(locate_template('framework/options/widget-popular-posts.php'));
include_once(locate_template('framework/options/widget-testimonial.php'));

/**
* Enable support for Post Thumbnails on posts and pages
*
*/

add_theme_support('post-thumbnails');
set_post_thumbnail_size( 1200, 9999 );

add_image_size('post-large', 795, 398, array('left', 'top'));
add_image_size('post-medium', 560, 280, array('left', 'top'));
add_image_size('post-widget', 400, 206, array('left', 'top'));
add_image_size('post-carousel', 1000, 800, array('left', 'top'));

/**
* Removes unwanted HTML markup elements in the header
*
*/

remove_action('wp_head', 'noindex', 1);
remove_action('wp_head', 'feed_links', 2);
remove_action('wp_head', 'feed_links_extra', 3);
remove_action('wp_head', 'rsd_link');
remove_action('wp_head', 'wlwmanifest_link');
remove_action('wp_head', 'index_rel_link');
remove_action('wp_head', 'parent_post_rel_link', 10, 0);
remove_action('wp_head', 'start_post_rel_link', 10, 0);
remove_action('wp_head', 'adjacent_posts_rel_link');
remove_action('wp_head', 'adjacent_posts_rel_link_wp_head', 10, 0 );
remove_action('wp_head', 'rest_output_link_wp_head', 10);
remove_action('wp_head', 'wp_oembed_add_discovery_links', 10);
remove_action('wp_head', 'check_and_publish_future_post');
remove_action('wp_head', 'wp_shortlink_wp_head', 10, 0);
remove_action('wp_head', 'wp_print_styles');
remove_action('wp_head', 'wp_generator');
remove_action('wp_head', 'rel_canonical');
remove_action('wp_head', 'locale_stylesheet');

/**
* Removes unwanted paragraph tags generated by wordpress
*
*/

remove_filter( 'the_content', 'wpautop' );
remove_filter( 'the_excerpt', 'wpautop' );

/**
* Removes unwanted emoji code in the header
*
*/

remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
remove_action( 'wp_print_styles', 'print_emoji_styles' );
remove_action( 'admin_print_styles', 'print_emoji_styles' );

/**
* Enqueuing scripts
*
*/

function cf_enqueue_scripts() {
    wp_deregister_script('jquery');
    wp_register_script('jquery', 'https://code.jquery.com/jquery-3.2.1.min.js');
    wp_enqueue_script('jquery');
    wp_enqueue_script('cf-scripts', THEME_ASSETS.'/js/script.min.js');
}

add_action( 'wp_enqueue_scripts', 'cf_enqueue_scripts' );

?>